# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clippy < Formula
  desc "Terminal clipboard history manager"
  homepage "https://github.com/bvdwalt/clippy"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bvdwalt/clippy/releases/download/v0.2.0/clippy_darwin_amd64.tar.gz"
      sha256 "10f7e860c05a3fc05955b25489ae600f77e7312d204d9e1d8e16f6e7e59766ad"

      define_method(:install) do
        bin.install "clippy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bvdwalt/clippy/releases/download/v0.2.0/clippy_darwin_arm64.tar.gz"
      sha256 "de18b85aba24dab98001fcb595587cd42705e3d73d7f6521007134190c43a936"

      define_method(:install) do
        bin.install "clippy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bvdwalt/clippy/releases/download/v0.2.0/clippy_linux_amd64.tar.gz"
      sha256 "0632bea0d2f9a40f854af4df99cd7f3af0c01e43d5ced6901c301a5e44f54acd"
      define_method(:install) do
        bin.install "clippy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bvdwalt/clippy/releases/download/v0.2.0/clippy_linux_arm64.tar.gz"
      sha256 "1f7d5ef60eb91c16115b5790c2488914bb88006af7618bb72c699640f352e0af"
      define_method(:install) do
        bin.install "clippy"
      end
    end
  end
end
