# This file was generated by GoReleaser. DO NOT EDIT.
cask "clippy" do
  version "0.5.0"

  on_macos do
    on_intel do
      url "https://github.com/bvdwalt/clippy/releases/download/v#{version}/clippy_darwin_amd64.tar.gz"
      sha256 "06ddaaf4535cccd6f0bbda13a06386912181b484e2faf3e3e64344e5f101dbea"
    end
    on_arm do
      url "https://github.com/bvdwalt/clippy/releases/download/v#{version}/clippy_darwin_arm64.tar.gz"
      sha256 "d192bac5300a85797a2b19aecf3fb9671786b5fbe7a184f23ecf6fb746fbf41c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bvdwalt/clippy/releases/download/v#{version}/clippy_linux_amd64.tar.gz"
      sha256 "d49581375c4a7f6c0a0c322594f1ea92c368f9e63172e4cba1fbd1c645793aa0"
    end
    on_arm do
      url "https://github.com/bvdwalt/clippy/releases/download/v#{version}/clippy_linux_arm64.tar.gz"
      sha256 "7a85273ab98c6c5c4f3c1b53f27c1c5d4397c23ebae5038c067587968762d8af"
    end
  end

  name "clippy"
  desc "Terminal clipboard history manager"
  homepage "https://github.com/bvdwalt/clippy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clippy"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clippy"]
  end

  # No zap stanza required

end
