# This file was generated by GoReleaser. DO NOT EDIT.
cask "clippy" do
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/clippy"]
  end

  version "0.13.2"

  on_macos do
    on_arm do
      sha256 "a6534dc236b48d7326b8f83767542b8c10eb3b109da1ea40e6d97e449f7c47fe"
      url "https://github.com/bvdwalt/clippy/releases/download/v#{version}/clippy_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5f0c5080f16cb7d4dfddf6771a513fed7c66876567797e273cb53f9d9bae6ce6"
      url "https://github.com/bvdwalt/clippy/releases/download/v#{version}/clippy_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "67f115b3077266b07ac79e90ab7d58785ec3b25893392d38200afcf296c2111d"
      url "https://github.com/bvdwalt/clippy/releases/download/v#{version}/clippy_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1ee4c6d209b5861478deda7642e2e39d04e192906e758dd03dee4da0b2c7e423"
      url "https://github.com/bvdwalt/clippy/releases/download/v#{version}/clippy_linux_amd64.tar.gz"
    end
  end

  name "clippy"
  desc "Terminal clipboard history manager"
  homepage "https://github.com/bvdwalt/clippy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clippy"

  # No zap stanza required
end
