# This file was generated by GoReleaser. DO NOT EDIT.
cask "clippy" do
  version "0.3.1"

  on_macos do
    on_intel do
      url "https://github.com/bvdwalt/clippy/releases/download/v#{version}/clippy_darwin_amd64.tar.gz"
      sha256 "ff8050316531f36021c8598409a17673a3005067e2b0e2439310ff276448f8b7"
    end
    on_arm do
      url "https://github.com/bvdwalt/clippy/releases/download/v#{version}/clippy_darwin_arm64.tar.gz"
      sha256 "de359096936a84a1736db0747295cac5585b3dd61ceecf7ffc76298e25fd35cd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bvdwalt/clippy/releases/download/v#{version}/clippy_linux_amd64.tar.gz"
      sha256 "9104ee126dff447956d13066c76592ba11ea147f7fa82c3b470733ae945affd8"
    end
    on_arm do
      url "https://github.com/bvdwalt/clippy/releases/download/v#{version}/clippy_linux_arm64.tar.gz"
      sha256 "b682804b041586060a0621a5db12cecd1c7dc54206b71f32f255f42775f33658"
    end
  end

  name "clippy"
  desc "Terminal clipboard history manager"
  homepage "https://github.com/bvdwalt/clippy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clippy"

  # No zap stanza required

end
