# This file was generated by GoReleaser. DO NOT EDIT.
cask "inkbase" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "841f782bfaaa09fd8769592130796fa7f185e3d197cce930a975b9994c363ecd"
      url "https://github.com/bvdwalt/inkbase/releases/download/v#{version}/inkbase_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bd85fb4cd8513f2ce9bd5b25e8f03872f2e0b26e63b3b559ebacaaca6057a7f1"
      url "https://github.com/bvdwalt/inkbase/releases/download/v#{version}/inkbase_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1777c39c4031c667d76da71197b0fd3af7e8f4b76415dca30d0c1b908a67ba97"
      url "https://github.com/bvdwalt/inkbase/releases/download/v#{version}/inkbase_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "98232b002b5ade9f22e849c0ffec9be2aa601b6e783ba91e52ecb7b197f38718"
      url "https://github.com/bvdwalt/inkbase/releases/download/v#{version}/inkbase_linux_arm64.tar.gz"
    end
  end

  name "inkbase"
  desc "Self-hosted markdown wiki for homelab notes"
  homepage "https://github.com/bvdwalt/inkbase"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inkbase"

  # No zap stanza required

end
