# This file was generated by GoReleaser. DO NOT EDIT.
cask "inkbase" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "ebd4bf0c90d1e81428fd97d4162a0f113084f14728aac0189eb87110e7f50c8b"
      url "https://github.com/bvdwalt/inkbase/releases/download/v#{version}/inkbase_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e3b509d92b90f597233b8e9d154e3892c137a3dc00995a5ced1bfa2745157573"
      url "https://github.com/bvdwalt/inkbase/releases/download/v#{version}/inkbase_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bbbcb6e3ea22c3052184f1e0da3d67c84bba8d5ed6f4dda8f35b403ebca561a7"
      url "https://github.com/bvdwalt/inkbase/releases/download/v#{version}/inkbase_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "38c2b1f87bf17f2adb2f0981075072a9eb41406f3c18cb176719f8203f42e918"
      url "https://github.com/bvdwalt/inkbase/releases/download/v#{version}/inkbase_linux_arm64.tar.gz"
    end
  end

  name "inkbase"
  desc "Self-hosted markdown wiki for homelab notes"
  homepage "https://github.com/bvdwalt/inkbase"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inkbase"

  # No zap stanza required

end
