# This file was generated by GoReleaser. DO NOT EDIT.
cask "inkbase" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "c4f73e4feec2b9112b1b36b7cf506c40907545f32939ffe08366508e3a75f1e9"
      url "https://github.com/bvdwalt/inkbase/releases/download/v#{version}/inkbase_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a1797b5bd5706f7ef97f26f24f8aec0930ab2f06d5536fd445faba231426683d"
      url "https://github.com/bvdwalt/inkbase/releases/download/v#{version}/inkbase_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "999e8c79f730eb063a2720f14a7caf252bcb6c8e8dfcbf45ccef7e31cca2a2c0"
      url "https://github.com/bvdwalt/inkbase/releases/download/v#{version}/inkbase_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d424e1bdb4ce79cd95c7a47828a38b09db13a308d342ff78ce9793681c2ff83"
      url "https://github.com/bvdwalt/inkbase/releases/download/v#{version}/inkbase_linux_arm64.tar.gz"
    end
  end

  name "inkbase"
  desc "Self-hosted markdown wiki for homelab notes"
  homepage "https://github.com/bvdwalt/inkbase"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inkbase"

  # No zap stanza required

end
