# This file was generated by GoReleaser. DO NOT EDIT.
cask "palimpsest" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "32188ec23f5f11d094bf7fe8f7491d36df567651f88ef3269f87f5390b7d2575"
      url "https://github.com/bvdwalt/palimpsest/releases/download/v#{version}/palimpsest_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "651d28f6bd336506996786c2080edad28726562075d8c25f9eecc9833e8aba20"
      url "https://github.com/bvdwalt/palimpsest/releases/download/v#{version}/palimpsest_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "95b0a898ab09fb06cad4bb5719856ab5d5d4b1b66925da0299b3b81f5a210ce3"
      url "https://github.com/bvdwalt/palimpsest/releases/download/v#{version}/palimpsest_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c65a47317365eb51994d36df3a35f28029b3ab0db528c4f65428b52b68c4a188"
      url "https://github.com/bvdwalt/palimpsest/releases/download/v#{version}/palimpsest_linux_arm64.tar.gz"
    end
  end

  name "palimpsest"
  desc "Self-hosted markdown wiki for homelab notes"
  homepage "https://github.com/bvdwalt/palimpsest"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "palimpsest"

  # No zap stanza required

end
