# This file was generated by GoReleaser. DO NOT EDIT.
cask "palimpsest" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "7d72f9958286e682ee61df0a877fa298154e0fca6dfc43bfdd9d5600bb7c0f00"
      url "https://github.com/bvdwalt/palimpsest/releases/download/v#{version}/palimpsest_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "72e1517af420d07192890dd9ccaf8c5a4a6cb7eccf514bec8db8e30a56d93508"
      url "https://github.com/bvdwalt/palimpsest/releases/download/v#{version}/palimpsest_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1e5b6a3ce729e949dd73d03c2782fa71bc26d37682e462c1932e26608572ead7"
      url "https://github.com/bvdwalt/palimpsest/releases/download/v#{version}/palimpsest_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "10f09275b22563847ab92feafaed698e1c66112c4dee090130b144686e5d4243"
      url "https://github.com/bvdwalt/palimpsest/releases/download/v#{version}/palimpsest_linux_arm64.tar.gz"
    end
  end

  name "palimpsest"
  desc "Self-hosted markdown wiki for homelab notes"
  homepage "https://github.com/bvdwalt/palimpsest"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "palimpsest"

  # No zap stanza required

end
