# This file was generated by GoReleaser. DO NOT EDIT.
cask "palimpsest" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "9b69fa3607c2bb38621d52b5ce576142558607fa004476626d05b45f5f624d54"
      url "https://github.com/bvdwalt/palimpsest/releases/download/v#{version}/palimpsest_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "47efac13548fa57d66ba0c3912e5503d02323b5a66360fdea95e06f7389083d1"
      url "https://github.com/bvdwalt/palimpsest/releases/download/v#{version}/palimpsest_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "671a5891c2800de8a40b352b2df778a52c897e18beebdd290fbc3f45f1c7f8b1"
      url "https://github.com/bvdwalt/palimpsest/releases/download/v#{version}/palimpsest_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7738d0211909a4eb31b4f5142b603c31e45b3378f2b249b5397965cd2636aa1b"
      url "https://github.com/bvdwalt/palimpsest/releases/download/v#{version}/palimpsest_linux_arm64.tar.gz"
    end
  end

  name "palimpsest"
  desc "Self-hosted markdown wiki for homelab notes"
  homepage "https://github.com/bvdwalt/palimpsest"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "palimpsest"

  # No zap stanza required

end
