# This file was generated by GoReleaser. DO NOT EDIT.
cask "pinger" do
  name "pinger"
  desc "Periodically pings HTTP endpoints on a configurable cron schedule"
  homepage "https://github.com/bvdwalt/pinger"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pinger"

  on_macos do
    on_intel do
      url "https://github.com/bvdwalt/pinger/releases/download/v#{version}/pinger_darwin_amd64.tar.gz"
      sha256 "de82542ba9cbe3b9df82cda6573702ad44adcf38c8e01e372d52c4c127977340"
    end
    on_arm do
      url "https://github.com/bvdwalt/pinger/releases/download/v#{version}/pinger_darwin_arm64.tar.gz"
      sha256 "a1509a3d60406f032e3c450d05b8c89d5a1f36b20527ae8f137689cee213bc4c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bvdwalt/pinger/releases/download/v#{version}/pinger_linux_amd64.tar.gz"
      sha256 "b61eadfc193b4b4d1cf4c490e5cfadb210e56b9f367f9f59a9cc42576a9a8505"
    end
    on_arm do
      url "https://github.com/bvdwalt/pinger/releases/download/v#{version}/pinger_linux_arm64.tar.gz"
      sha256 "53b40c9752a5e57cd2709dcba9cba7a1707f9682045cd2617906310693df7df7"
    end
  end

  # No zap stanza required
end
