# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clippy < Formula
  desc "Terminal clipboard history manager"
  homepage "https://github.com/bvdwalt/clippy"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bvdwalt/clippy/releases/download/v0.3.2/clippy_darwin_amd64.tar.gz"
      sha256 "449ccd676b79dc8169eec793fa398a51bead8c32d150b99d062e1de8cf23e4f7"

      define_method(:install) do
        bin.install "clippy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bvdwalt/clippy/releases/download/v0.3.2/clippy_darwin_arm64.tar.gz"
      sha256 "18cfa0768e26105d02c810bc5ce4e3c017114b26587997e857794f6b660ff51c"

      define_method(:install) do
        bin.install "clippy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bvdwalt/clippy/releases/download/v0.3.2/clippy_linux_amd64.tar.gz"
      sha256 "2f57e35a4f66eff94a792731d9d0e8b8447e4172657e62d53f6b7eaad9e6ed26"
      define_method(:install) do
        bin.install "clippy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bvdwalt/clippy/releases/download/v0.3.2/clippy_linux_arm64.tar.gz"
      sha256 "21559dbd9ac0fece25a4cbbdb2e0a1ba86f52bbad36e425260c88f55571e2fac"
      define_method(:install) do
        bin.install "clippy"
      end
    end
  end
end
